# Generated by Django 4.1.7 on 2023-04-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='category_dashboard',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
