# Generated by Django 4.1.7 on 2023-04-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_cashflow_category_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='debit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
