# Generated by Django 4.1.7 on 2023-04-05 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('cashflow', '0003_alter_cashflow_credit_alter_cashflow_debit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_user', to='profiles.customuser'),
        ),
    ]
