# Generated by Django 4.1.7 on 2023-03-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_categories_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='Category',
            new_name='category_name',
        ),
    ]
