# Generated by Django 4.1.7 on 2023-04-05 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('categories', '0003_rename_category_categories_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='profiles.customuser'),
        ),
    ]
